# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD to Google App Engine

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    #     strategy:
    #       matrix:
    #         node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy to Google App Engine
        #       env:
        #         CLIENT_ID: ${{ secrets.CLIENT_ID }}
        #         SECRET: ${{ secrets.SECRET }}
        uses: actions/setup-node@v1
        with:
          node-version: v11.10.1
      - run: npm ci
        env:
          CI: false
      #       build client
      - run: cd client && npm i && npm run build
        env:
          CI: false
      #     - run: npm run build --if-present
      #     - run: npm test
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          # An optional variables parameter can be used
          gae_variables: ${{ secrets.GCP_VARIABLES }}

      - name: Publish app to Google App Engine
        run: |
          # This client-secret.json is converted by GCP_SA_KEY.
          gcloud auth activate-service-account ${{ secrets.GCP_SA }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy app.yaml --promote
